server {
    listen 80;
    server_name 207.148.124.127;

    root /var/www/sport-lottery-predictor;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|json|csv)$ {
        expires 5m;
        add_header Cache-Control "public";
    }
}
