server {
    listen 80;
    server_name 207.148.124.127;

    location = /sport {
        return 301 /sport/;
    }

    location /sport/ {
        alias /var/www/sport-lottery-predictor/;
        index index.html;
        try_files $uri $uri/ /sport/index.html;
        expires 5m;
        add_header Cache-Control "public";
    }
}
